reload:
  message:
    - "&cTackl &7Arena &6Reloaded!"

spawn:
  coords:
    world: "arenas"
    x: 51
    y: 4
    z: 10
    
match:
  match_end_message:
    - "&6-=-=-=-=-=-=-=-"
    - "&aDamage Dealt: &l%tacklarena_playerdamagegiven%"
    - "&cDamage Taken: &l%tacklarena_playerdamagetaken%"
    - "&6-=-=-=-=-=-=-=-"

mystats:
  - "&aWins: &l%tacklarena_playerwins%"
  - "&cLosses: &l%tacklarena_playerlosses%"
  - "&aOverall Damage Dealt: &l%tacklarena_playeroveralldamagegiven%"
  - "&cOverall Damage Taken: &l%tacklarena_playeroveralldamagetaken%"
      

MySQL:
  host: "0"
  database: "0"
  user: "0"
  pass: "0"
  port: 0000
